[2025-05-26T21:50:19.552+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-26T21:50:19.569+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_etl_dag.fetch_and_store_currency scheduled__2025-05-26T17:00:00+00:00 [queued]>
[2025-05-26T21:50:19.573+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_etl_dag.fetch_and_store_currency scheduled__2025-05-26T17:00:00+00:00 [queued]>
[2025-05-26T21:50:19.573+0300] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-05-26T21:50:19.589+0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_and_store_currency> on 2025-05-26 17:00:00+00:00
[2025-05-26T21:50:19.592+0300] {standard_task_runner.py:63} INFO - Started process 25241 to run task
[2025-05-26T21:50:19.595+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'currency_etl_dag', 'fetch_and_store_currency', 'scheduled__2025-05-26T17:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/currency_dag.py', '--cfg-path', '/tmp/tmp26e0ftth']
[2025-05-26T21:50:19.596+0300] {standard_task_runner.py:91} INFO - Job 15: Subtask fetch_and_store_currency
[2025-05-26T21:50:19.640+0300] {task_command.py:426} INFO - Running <TaskInstance: currency_etl_dag.fetch_and_store_currency scheduled__2025-05-26T17:00:00+00:00 [running]> on host Home.
[2025-05-26T21:50:19.692+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='currency_etl_dag' AIRFLOW_CTX_TASK_ID='fetch_and_store_currency' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-26T17:00:00+00:00'
[2025-05-26T21:50:19.693+0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-26T21:50:20.623+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-26T21:50:20.624+0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imsim/currency_pipeline/airflow/dags/fetch_currency_data.py", line 28, in fetch_and_store_currency
    for currency, rate in data["rates"].items():
                          ~~~~^^^^^^^^^
KeyError: 'rates'
[2025-05-26T21:50:20.629+0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=currency_etl_dag, task_id=fetch_and_store_currency, run_id=scheduled__2025-05-26T17:00:00+00:00, execution_date=20250526T170000, start_date=20250526T185019, end_date=20250526T185020
[2025-05-26T21:50:20.644+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task fetch_and_store_currency ('rates'; 25241)
[2025-05-26T21:50:20.656+0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-26T21:50:20.665+0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-26T21:50:20.665+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
